services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./webroot/:/var/www/html
    networks:
      - laravel-network

  webserver:
    image: nginx:alpine
    container_name: webserver
    ports:
      - "8000:80"
    volumes:
      - ./webroot/:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - laravel-network

  postgres:
    image: postgres:latest
    container_name: postgresDB
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD:  1111
    ports:
      - "5432:5432"
    networks:
      - laravel-network
    
  pdadmin:
    image: dpage/pgadmin4:snapshot
    container_name: pdadmin
    ports:
      - 8080:80
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    restart: unless-stopped
    depends_on:
      - postgres
    networks:
      - laravel-network


networks:
  laravel-network:
    driver: bridge